#!/usr/bin/env python3
"""Generate or edit ECHO production image candidates with OpenAI GPT-Image-2.

Credentials are never stored in the repository. The runner accepts either:
- OPENAI_API_KEY from the process environment, or
- a macOS Keychain generic password whose service defaults to `openai-api-key`.

Generated bytes are written only to asset_pipeline/source/generated/. They are
NOT automatically approved, integrated, committed, or pushed. Use
import_generated_image.py after human/visual QA.
"""

from __future__ import annotations

import argparse
import base64
import os
from pathlib import Path
import subprocess
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
PROMPT_DIR = REPO_ROOT / "asset_pipeline" / "prompts"
OUT_DIR = REPO_ROOT / "asset_pipeline" / "source" / "generated"
DEFAULT_MODEL = "gpt-image-2"
DEFAULT_SIZE = "1536x1024"
DEFAULT_QUALITY = "high"


def fail(message: str, code: int = 1) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(code)


def load_key(service: str) -> str:
    env = os.getenv("OPENAI_API_KEY", "").strip()
    if env:
        return env
    proc = subprocess.run(
        ["security", "find-generic-password", "-s", service, "-w"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.strip()
    fail(
        "OpenAI API credential not found. Set OPENAI_API_KEY locally or add a "
        f"macOS Keychain generic password with service '{service}'. Do not paste the key into chat."
    )
    raise AssertionError


def read_prompt(path: Path) -> str:
    if not path.is_file():
        fail(f"prompt file not found: {path}")
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        fail(f"prompt file is empty: {path}")
    return text


def extract_image_bytes(result: Any) -> bytes:
    if not getattr(result, "data", None):
        fail("OpenAI returned no image data")
    item = result.data[0]
    b64 = getattr(item, "b64_json", None)
    if b64:
        return base64.b64decode(b64)
    url = getattr(item, "url", None)
    if url:
        # Avoid adding a requests dependency solely for fallback URL responses.
        from urllib.request import urlopen
        with urlopen(url) as r:  # nosec - URL is supplied by OpenAI API response
            return r.read()
    fail("OpenAI image response contained neither b64_json nor URL")
    raise AssertionError


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate an ECHO image candidate with GPT-Image-2")
    ap.add_argument("--asset-id", required=True)
    ap.add_argument("--prompt", help="Prompt markdown path; defaults to asset_pipeline/prompts/<asset-id>.md")
    ap.add_argument("--mode", choices=["generate", "edit"], default="generate")
    ap.add_argument("--input", help="Required source image for edit mode")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--size", default=DEFAULT_SIZE)
    ap.add_argument("--quality", default=DEFAULT_QUALITY)
    ap.add_argument("--keychain-service", default="openai-api-key")
    ap.add_argument("--suffix", default="v1", help="Candidate suffix, e.g. v1/v2")
    args = ap.parse_args()

    prompt_path = Path(args.prompt).expanduser() if args.prompt else PROMPT_DIR / f"{args.asset_id}.md"
    if not prompt_path.is_absolute():
        prompt_path = REPO_ROOT / prompt_path
    prompt = read_prompt(prompt_path.resolve())

    api_key = load_key(args.keychain_service)
    try:
        from openai import OpenAI
    except ImportError:
        fail("Python package 'openai' is not installed. Run asset_pipeline/setup_imagegen_env.sh first.")

    client = OpenAI(api_key=api_key)
    print(f"MODEL={args.model}")
    print(f"MODE={args.mode}")
    print(f"ASSET={args.asset_id}")
    print(f"SIZE={args.size}")
    print(f"QUALITY={args.quality}")

    if args.mode == "edit":
        if not args.input:
            fail("--input is required for edit mode")
        src = Path(args.input).expanduser().resolve()
        if not src.is_file():
            fail(f"edit input does not exist: {src}")
        with src.open("rb") as image_file:
            result = client.images.edit(
                model=args.model,
                image=image_file,
                prompt=prompt,
                size=args.size,
                quality=args.quality,
                input_fidelity="high",
                output_format="png",
                response_format="b64_json",
                n=1,
            )
    else:
        if args.input:
            fail("--input is only valid in edit mode")
        result = client.images.generate(
            model=args.model,
            prompt=prompt,
            size=args.size,
            quality=args.quality,
            output_format="png",
            response_format="b64_json",
            n=1,
        )

    data = extract_image_bytes(result)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    target = OUT_DIR / f"{args.asset_id}_{args.suffix}.png"
    if target.exists():
        fail(f"candidate already exists: {target}; choose a new --suffix")
    target.write_bytes(data)
    print(f"OUTPUT={target.relative_to(REPO_ROOT)}")
    print(f"BYTES={len(data)}")
    print("STATUS=generated_candidate_qa_required")


if __name__ == "__main__":
    main()
